host: localhost:8080
info:
  contact:
    email: kokoulin92@gmail.com
  description: URL Shortener Service
  title: Shortener API
  version: "1.0"
paths:
  /:
    post:
      consumes:
      - application/json
      description: method to get a single long url by a short url
      operationId: createShortURL
      parameters:
      - description: Contains a string with an url
        in: body
        name: url_data
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "307":
          description: Temporary Redirect
          schema:
            type: string
        "400":
          description: the parameter is missing
          schema:
            type: string
        "404":
          description: the parameter not found
          schema:
            type: string
        "410":
          description: the parameter was deleted
          schema:
            type: string
      summary: method to save a single url
  /{id}:
    get:
      consumes:
      - application/json
      description: method to get a single long url by a short url
      operationId: retrieveShortURL
      parameters:
      - description: ShortURL
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "307":
          description: Temporary Redirect
          schema:
            type: string
        "400":
          description: the parameter is missing
          schema:
            type: string
        "404":
          description: the parameter not found
          schema:
            type: string
        "410":
          description: the parameter was deleted
          schema:
            type: string
      summary: method to get a single long url
swagger: "2.0"
